version: '3.3'

services:

    app:
      build:
        context: .
        dockerfile: app.dockerfile
      container_name: MSPM-APP-CONTAINER
      restart: unless-stopped
      working_dir: /var/www
      environment:
        SERVICE_NAME: app
        SERVICE_TAGS: dev
      volumes:
       - ./:/var/www
       - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
      networks:
        default:
          aliases:
            - ${PHP_FPM_HOST}

    webserver:
      image: nginx:alpine
      container_name: MSPM-WEB-SERVER-CONTAINER
      restart: unless-stopped
      ports:
        - ${NGINX_PORT}:${NGINX_PORT}
        - ${NGINX_SECURE_PORT}:${NGINX_SECURE_PORT}
      volumes:
        - ./:/var/www
        - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
      networks:
          default:
            aliases:
              - ${NGINX_HOST}

    db:
      image: mysql:5.7.22
      command: --default-authentication-plugin=mysql_native_password
      restart: always
      container_name: MSPM-MYSQL-CONTAINER
      environment:
        MYSQL_DATABASE: ${MYSQL_DATABASE}
        MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        SERVICE_TAGS: dev
        SERVICE_NAME: mysql
      ports:
        - ${DB_PORT}:${DB_PORT}
      volumes:
        - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
        - ./docker/mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      networks:
        default:
          aliases:
            - ${DB_HOST}

    phpmyadmin:
      image: phpmyadmin/phpmyadmin
      restart: always
      container_name: MSPM-PHPMYADMIN-CONTAINER
      environment:
        PMA_ARBITRARY: ${PMA_ARBITRARY}
        PMA_HOST: ${DB_HOST}
      ports:
        - ${PMA_PORT}:80
      depends_on:
        - db
      networks:
          default:
            aliases:
              - ${PMA_HOST}

networks:
  default:
    driver: bridge
